updated 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,31 +1,84 @@
 #!/usr/bin/env bash
-# Installs and configures an nginx web server
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Install and set-up nginx
-sudo apt-get update && \
-sudo apt-get -y install nginx ufw && \
+# uncomment to see the script run in action
+#set -x
+
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
-# change the default response
-echo 'Hello World!' | sudo tee /var/www/html/index.html
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-# setup redirect
-replacement_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n"
-sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-# setup 404
-error_replacement_string="server_name _;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
-sudo sed -i "s/server_name _;/$error_replacement_string/" /etc/nginx/sites-enabled/default
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# Setup headers
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-host_name=$(hostname)
-search_text="listen \[\:\:\]\:80 default_server;"
-replacement_text="$search_text\n\n\tadd_header X-Served-By $host_name;\n"
-sudo sed -i "s/$search_text/$replacement_text/" /etc/nginx/sites-enabled/default
-sudo service nginx restart#!/usr/bin/env bash
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-# Restart nginx
-sudo service nginx restart
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
